# 获取所有用户信息
GET http://localhost:8080/v1/user HTTP/1.1
###

POST http://localhost:8080/v1/user HTTP/1.1
content-type: application/json

{
    "tel":13265485486,
    "email": "gy@outlook.com",
    "password": "admin", 
}